name: sftp-server

services:
  sftp-server:
    # image: sftp:latest
    build:
      dockerfile: Dockerfile
    ports:
      - 22:22
    networks:
      default:
        aliases:
          - wso2-sftp
